### ISSUE TITLE
On reporting FID for inverse problems

### ISSUE THREAD

**Issue by Adhithyan8** [annegnx/PnP-Flow#1]
Hi,

Just a concern on reporting the FID for inverse tasks like inpainting. The metric only measures if the original image set and say the inpainted image set are from the same distribution right? (Or atleast how far apart this first and second moments are).

Here we ignore the one to one correspondence between the original images and its generated counter-parts. So does it make sense to report the FID here?

For example, if I generate a completely unrelated "real" image for an inpainting task, I will still get a very low FID while clearly not doing the task as expected.

**Comment by PaulLyonel** [comment]
Hi, 

yes, indeed this is a problem of FID. Note that in our code and paper we do not use FID for benchmarking. It is only included for model training purposes. 

We measure PSNR, SSIM and LPIPS for the benchmarking of the inverse problem reconstructions. Note that however PSNR can be also misleading in the particular case of inpainting, as there might be several "possible" reconstructions and feature based metrics might be more useful here (like LPIPS).

**Comment by Adhithyan8** [comment]
Hi,

Thanks a lot for clarifying this. I think I was thrown off by the FID values in d_flow and ot_ode papers which of course you have only provided for comparison. 

And also, great job on the open source implementation collecting these different works. This repo has been incredibly helpful and accessible :)

**Comment by PaulLyonel** [comment]
Thanks for the kind words, we appreciate this! 

Note that in https://arxiv.org/abs/2111.13606 for this reason they propose to measure joint fid, i.e., the fid on the joint distributions (x,y), which measures realism and inverse problem relation.
